language: node_js
node_js:
- node
deploy:
  provider: npm
  email: marvin@luchs.org
  api_key:
    secure: RWF+rAzLg7w10Pog5PM0GT0XPCxWe6UeIeR0cr1Dhww0AShWUEkbRI4U1qji9FM72muAa0GcOxVBVbZL0ZtRJOmhqpzDk9AGYLe6KjWnctLJtlebvpgUZ+xL18o3pcpHyZmvTtTK2+fhPCtYc0t5X8TaL3IqCa1NGKMszRatc7UKfz60DBR55nNJyzE19UythyUNH847RrRSg8IGr6HAD0UHj429K+/x8HaI+8Ls2+VP8/XnO2pTUKQhnoSOt6op3gEOM36czqybtpaKDtkSmPNSvOk6AhFP/8uEt/Tz2zWEG64RNTzyzmuthVdP5EkRHGjB3ym4BpvKZlhgh12R+1fw0kbV2o0RfyNkMx/YmuffNozNk9h9GyiY6BhhpQyGDOAtCX1g8Ij09E4VTtMdwNsZ8AI8xA3E2chAYvowy1A/ucPmdAQnv8fKAnVWVSlJsbGpCjgUWYGXjnIbE/hH309T0t8XlYinPhYRJ/Qk1LEu5px5gBPUH3jXRlRtxON5eydvGleDmjSqH/vGqfAV81V2wk82d1Qh75Y1nV8ckuAim4YQnjKp0dadHblLfg9Sjye7tHE1fNyZjR8XwMwIaKTlGCB1wA3JJUGmx7KKwaKT5BxuZLjnJNLSvXaD8PNImfL8RZ1coGFPUA9unPvVGvq+Mqjmg/hKKqqCkGaa3Zk=
  on:
    tags: true
